# -----------------------------------------------------------------------------
# Make pPLATO
# -----------------------------------------------------------------------------

# compiler flags


STATDIR = ../stat_calc
DATADIR = ../data_manage
GADIR = ../galib247
GEDIR = ../libGE-0.26

INCLUDEDIR = -I. -I$(STATDIR) -I$(DATADIR) -I$(GADIR) -I$(GEDIR)
#CCFLAGS = -Wall -O2 $(INCLUDEDIR)
#DFLAGS = -DPARALLEL
#DFLAGS = 
CCFLAGS = -m64 -Wall $(DFLAGS) -O2 $(INCLUDEDIR)
#CCFLAGS = -Wall $(DFLAGS) -g $(INCLUDEDIR)

GALIBLIB = ../galib247/ga
GELIBLIB = ../libGE-0.26

LIBDIR = -L$(GALIBLIB) -L$(GELIBLIB) -L../lib 
LIBS = -lm -lga -lGE -ldata_manage -lstat_calc
PROG_NAME = hemann
EXECUTABLE = hemann

SYSOBJS = AlgorithmFactory.o BalAccCalculator.o CalculatorFactory.o Config.o \
	ConfigFileReader.o GE1DArrayGenome.o GENNGrammarAdjuster.o GEObjective.o \
	hemann.o InitGEgenome.o MeanSquaredErrCalculator.o NNSolution.o \
	NNSolutionCreator.o OutputManager.o Population.o Solution.o \
	SolutionFactory.o Terminals.o TerminalSymbCreator.o TerminalSymbol.o \
	GENNAlg.o NNSolutionCreatorIncludeAll.o NNSolutionCreatorIncludeOnce.o \
	ExpressionTree.o NNLog.o Algorithm.o RSquaredCalculator.o BioFilterReader.o \
	HemannGrammarSI.o BioFilterModelCollection.o

SYSHEADERS = AlgorithmFactory.h Algorithm.h AlgorithmList.h BalAccCalculator.h \
	CalculatorFactory.h CalculatorList.h ConfigFileReader.h Config.h \
	GE1DArrayGenome.h GENNAlg.h GENNGrammarAdjuster.h GEObjective.h \
	HemannExcept.h InitGEgenome.h MeanSquaredErrCalculator.h NNSolution.h \
	NNSolutionCreator.h OutputManager.h Population.h rbtree.h \
	SolutionCalculator.h SolutionCreator.h SolutionFactory.h Solution.h \
	Terminals.h TerminalSymbCreator.h TerminalSymbol.h RSquaredCalculator.h \
	NNSolutionCreatorIncludeAll.h NNSolutionCreatorIncludeOnce.h \
	ExpressionTree.h Tree.hh AlgorithmLog.h NNLog.h BioFilterReader.h \
	HemannGrammarSI.h BioFilterModelCollection.h

ifeq ($(DFLAGS),-DPARALLEL)
CC = mpiCC
SYSOBJS += TransferData.o
SYSHEADERS += TransferData.h
EXECUTABLE = hemannp
else
CC = g++
endif

all: $(PROG_NAME)

$(PROG_NAME): $(SYSOBJS) $(SYSHEADERS)
	$(CC) -o ../bin/$(EXECUTABLE) $(SYSOBJS) $(LIBDIR) $(LIBS)

%.o: %.cpp $(SYSHEADERS) 
	$(CC) -c $(CCFLAGS) $< -o $@

tarball:
	tar cvfz hemann_source_`date '+%Y%m%d'`.tar.gz \
	*.cpp *.h* Makefile* 

clean:
	rm -f *.o *~ core

